// <auto-generated>
// Generated by OpenAPI Generator. Do not edit this file manually.
// </auto-generated>

export type TicketDto = {
  id?: string;
  title?: string;
  status?: string;
};

export async function getTicket(id: string): Promise<TicketDto> {
  const response = await fetch(`/api/tickets/${id}`);
  const ticket = await response.json();

  // Local patch: the upstream API sometimes returns null status.
  if (!ticket.status) {
    ticket.status = "open";
  }

  return ticket;
}

