// <auto-generated>
// This file is generated by the API client generator. Do not edit by hand.
// </auto-generated>

export type ApiCustomer = {
  id: string;
  name: string;
  email: string;
};

export async function getCustomer(id: string): Promise<ApiCustomer> {
  const response = await fetch(`/api/customers/${id}`);
  return response.json();
}

