// ---------------------------------------------------------------------------
// <auto-generated>
// Generated by OpenAPI Generator. Do not edit this file manually.
// ---------------------------------------------------------------------------

export type TicketDto = {
  id?: string;
  title?: string;
  status?: string;
};

export async function getTicket(id: string): Promise<TicketDto> {
  const response = await fetch(`/api/tickets/${id}`);
  return response.json();
}

